from accounts import views
from django.urls import path
from django.urls import include


urlpatterns = [
    path(
        "customer/account/",
        include(
            (
                [
                    path(
                        route="signup/",
                        view=views.account_signup_view,
                        name="account_signup",
                    ),
                    path(
                        route="login/",
                        view=views.account_login_view,
                        name="account_login",
                    ),
                    path(
                        route="reset-password/",
                        view=views.account_request_password_reset_view,
                        name="account_reset_password",
                    ),
                    path(
                        route="reset-password/<uidb64>/<token>/",
                        view=views.account_request_password_reset_view,
                        name="account_reset_password",
                    ),
                    path(
                        route="set-new-password/<uidb64>/<token>/",
                        view=views.account_set_new_password_view,
                        name="set_new_password",
                    ),
                    path(
                        route="logout/",
                        view=views.account_logout_view,
                        name="account_logout",
                    ),
                ],
                "accounts",
            ),
            namespace="auth_views",
        ),
    ),
    path(
        "customer/",
        include(
            (
                [
                    path(
                        route="account/index/",
                        view=views.dashboard_view,
                        name="profile",
                    ),
                    path(
                        route="order/index/",
                        view=views.order_list_view,
                        name="order_list",
                    ),
                    path(
                        route="order/detail/<int:pk>/",
                        view=views.order_detail_view,
                        name="order_detail",
                    ),
                    path(
                        route="settings/<str:slug>/",
                        view=views.settings_view,
                        name="update",
                    ),
                ],
                "accounts",
            ),
            namespace="dashboard_users",
        ),
    ),
    path(
        "sp-marketplace-delivery/",
        include(
            (
                [
                    path(
                        route="register/",
                        view=views.distributor_register_view,
                        name="delivery_register",
                    ),
                    path(
                        route="success/<int:delivery_id>/",
                        view=views.distributor_register_success_view,
                        name="delivery_register_success",
                    ),
                ],
                "accounts",
            ),
            namespace="delivery",
        ),
    ),
]
