# Generated by Django 3.2.12 on 2022-03-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=225, verbose_name='adresse ip')),
                ('tracking_id', models.CharField(db_index=True, default='', max_length=50)),
                ('date_viewed', models.DateField(auto_now=True, verbose_name='date de visite')),
                ('time_viewed', models.TimeField(auto_now=True, verbose_name='heure de visite')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product', verbose_name='produit')),
            ],
            options={
                'verbose_name_plural': 'statistiques',
                'db_table': 'analiytics_db',
                'ordering': ('-date_viewed', '-time_viewed'),
                'get_latest_by': ('-date_viewed', '-time_viewed'),
                'abstract': False,
                'index_together': {('tracking_id',)},
            },
        ),
    ]
