# Generated by Django 3.1.6 on 2021-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='time_viewed',
            field=models.TimeField(auto_now=True, verbose_name='heure de visite'),
        ),
    ]
