# Generated by Django 3.1.5 on 2021-01-25 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom & prénoms')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('phone', models.CharField(max_length=150, verbose_name='téléphone')),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='sujet de la requete')),
                ('enterprise', models.CharField(blank=True, max_length=150, null=True, verbose_name='entreprise')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
        ),
    ]
