# Generated by Django 3.2.12 on 2022-03-09 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='URL de la boutique')),
                ('parent', models.CharField(blank=True, max_length=120, null=True, verbose_name='titre de la campagne')),
                ('name', models.CharField(blank=True, choices=[('Destockage', 'Destockage'), ('Vente Flash', 'Vente Flash'), ('Nouvelle Arrivage', 'Nouvelle Arrivage')], default='Vente Flash', max_length=120, null=True, verbose_name='campagne')),
                ('image', models.ImageField(upload_to=helpers.utils.upload_campign_image_path, verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Campagnes',
                'db_table': 'campaign_db',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom & prénoms')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('phone', models.CharField(max_length=150, verbose_name='téléphone')),
                ('subject', models.CharField(max_length=150, verbose_name='sujet de la requete')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='entreprise')),
                ('message', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'messages',
                'db_table': 'contact_db',
                'ordering': ['-timestamp'],
                'get_latest_by': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='URL de la boutique')),
                ('activate_at', models.BooleanField(default=False, help_text='Cette promotion est active ?', verbose_name='promotion active ?')),
            ],
            options={
                'verbose_name_plural': 'promotions',
                'db_table': 'promotion_db',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='URL de la boutique')),
                ('name', models.CharField(blank=True, help_text='Saisir le titre de la publicité', max_length=225, null=True, verbose_name='Titre')),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'flv', 'mov', 'ogv', '3gp', '3g2', 'wmv', 'mpeg', 'flv', 'mkv', 'avi'])])),
                ('is_active', models.BooleanField(default=False, verbose_name='actif/inactif ?')),
            ],
            options={
                'verbose_name_plural': 'Publicités',
                'db_table': 'pub_db',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Entrer le nom et prénoms du client', max_length=120, verbose_name='nom & prénoms')),
                ('status_client', models.CharField(blank=True, help_text='Entrer le statut du client', max_length=120, null=True, verbose_name='Statut (entrepreneur/boutique/etc)')),
                ('message', models.TextField(help_text='Entrer le message du client', verbose_name='message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_image/', verbose_name='image')),
                ('activate_at', models.BooleanField(default=False, help_text='rendre visible cet témoignage ?', verbose_name='actif')),
            ],
            options={
                'verbose_name_plural': 'Témoignage',
                'db_table': 'testimonial_db',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pub',
            index=models.Index(fields=['id'], name='pub_db_id_c83b8d_idx'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='pages.campaign', verbose_name='campagne'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(help_text='Choisir un produit à mettre en promotion', on_delete=django.db.models.deletion.CASCADE, related_name='promotions_products', to='catalogue.product', verbose_name='produits'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='store'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['id'], name='campaign_db_id_5a35b9_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['id'], name='id_promotion'),
        ),
    ]
