# Generated by Django 3.1.6 on 2021-02-11 17:19

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210209_0203'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': ['-timestamp'], 'ordering': ['-timestamp'], 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact_db',
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to', models.SlugField(max_length=100, verbose_name='lien')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.upload_image_path, verbose_name='image')),
                ('title', models.CharField(max_length=120, verbose_name='Titre de la promotion')),
                ('active', models.BooleanField(default=False, verbose_name='validité de la promotion')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de creation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='promotion')),
            ],
            options={
                'verbose_name_plural': 'promotion',
                'db_table': 'promotion_db',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
                'unique_together': {('link_to',)},
                'index_together': {('link_to', 'title')},
            },
        ),
    ]
