# Generated by Django 3.1.6 on 2021-02-11 17:50

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210211_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=False, verbose_name='promotion active ?'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_promotion_image_path, verbose_name='image'),
        ),
    ]
