# Generated by Django 3.1.5 on 2021-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210125_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Message'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(default=1, max_length=150, verbose_name='entreprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom & prénoms'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=150, verbose_name='sujet de la requete'),
            preserve_default=False,
        ),
    ]
