# Generated by Django 3.1.5 on 2021-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210125_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'message'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name_plural': 'abonnement'},
        ),
        migrations.AddField(
            model_name='contact',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse ip'),
        ),
    ]
