# Generated by Django 3.1.5 on 2021-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='adresse ip'),
        ),
    ]
