# Generated by Django 3.1.5 on 2021-01-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210125_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='adresse_ip',
        ),
    ]
