# Generated by Django 3.2.12 on 2022-05-19 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import helpers.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='URL de la boutique')),
                ('shipping_first_name', models.CharField(max_length=50, verbose_name='nom de famille')),
                ('shipping_last_name', models.CharField(max_length=50, verbose_name='prénom')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='numéro de téléphone')),
                ('phone_two', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='téléphone supplémentaire (facultatif)')),
                ('shipping_city', models.CharField(max_length=50, verbose_name='ville')),
                ('shipping_country', django_countries.fields.CountryField(max_length=2, verbose_name='pays/région')),
                ('shipping_adress', models.CharField(max_length=50, verbose_name='situation géographique')),
                ('shipping_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='adresse postal (facultatif)')),
                ('note', models.TextField(blank=True, max_length=120, null=True, verbose_name='note de commande (facultatif)')),
                ('civility', models.CharField(choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='M.', max_length=4, verbose_name='civilité')),
                ('store_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID BOUTIQUE')),
                ('email', models.EmailField(error_messages={'unique': 'Un utilisateur disposant de ce courriel existe déjà.'}, max_length=254, unique=True, verbose_name='email')),
                ('store', models.CharField(error_messages={'unique': 'Un magasin disposant de ce nom existe déjà.'}, max_length=80, unique=True, verbose_name='boutique')),
                ('store_description', models.TextField(blank=True, max_length=254, null=True, verbose_name='description de la boutique')),
                ('logo', models.ImageField(blank=True, default='static/img/default.jpeg', help_text='Ajouter le logo de votre boutique', null=True, upload_to=helpers.utils.upload_image_logo_path, verbose_name='logo')),
                ('is_seller', models.BooleanField(default=False, verbose_name='statut vendeur')),
                ('is_staff', models.BooleanField(default=False, verbose_name='statut équipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='statut administrateur')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='date de derniere connexion')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
            ],
            options={
                'verbose_name_plural': 'boutiques',
                'ordering': ('-date_joined', '-last_login'),
                'get_latest_by': ('-date_joined', '-last_login'),
            },
        ),
        migrations.CreateModel(
            name='GuestCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_first_name', models.CharField(max_length=50, verbose_name='nom de famille')),
                ('shipping_last_name', models.CharField(max_length=50, verbose_name='prénom')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='numéro de téléphone')),
                ('phone_two', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='téléphone supplémentaire (facultatif)')),
                ('shipping_city', models.CharField(max_length=50, verbose_name='ville')),
                ('shipping_country', django_countries.fields.CountryField(max_length=2, verbose_name='pays/région')),
                ('shipping_adress', models.CharField(max_length=50, verbose_name='situation géographique')),
                ('shipping_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='adresse postal (facultatif)')),
                ('note', models.TextField(blank=True, max_length=120, null=True, verbose_name='note de commande (facultatif)')),
                ('email', models.EmailField(error_messages={'unique': 'Un utilisateur disposant de ce courriel existe déjà.'}, max_length=254, unique=True, verbose_name='email')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'acheteur(s)',
                'ordering': ('-created_at', '-active'),
                'get_latest_by': ('-created_at', '-active'),
            },
        ),
        migrations.CreateModel(
            name='ProfileSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(blank=True, help_text='Copier at coller le lien facebook de votre page ici.', max_length=250, null=True, verbose_name='compte facebook')),
                ('instagram', models.URLField(blank=True, help_text='Copier at coller le lien instagram de votre page ici.', max_length=250, null=True, verbose_name='compte instagram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name_plural': 'profile reseaux sociaux',
            },
        ),
        migrations.AddIndex(
            model_name='guestcustomer',
            index=models.Index(fields=['id'], name='accounts_gu_id_9af536_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='profilesocialmedia',
            index=models.Index(fields=['id'], name='accounts_pr_id_42c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='accounts_us_id_b41dd0_idx'),
        ),
    ]
