# Generated by Django 3.1.5 on 2021-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='lien facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagramm',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='lien instagramm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='lien linkedin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='lien twitter'),
        ),
    ]
