# Generated by Django 3.1.5 on 2021-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intagramm',
        ),
        migrations.AddField(
            model_name='user',
            name='instagramm',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='instagramm'),
        ),
    ]
