# Generated by Django 3.2.12 on 2022-11-29 02:11
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipping_first_name",
                    models.CharField(max_length=50, verbose_name="nom de famille"),
                ),
                (
                    "shipping_last_name",
                    models.CharField(max_length=50, verbose_name="prénom"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="numéro de téléphone"
                    ),
                ),
                (
                    "phone_two",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="téléphone supplémentaire (facultatif)",
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=50, verbose_name="ville"),
                ),
                (
                    "shipping_country",
                    models.CharField(
                        choices=[
                            (None, "Veuillez sélectionner un pays"),
                            ("Côte d'Ivoire", "Côte d'Ivoire"),
                        ],
                        default="Côte d'Ivoire",
                        max_length=25,
                        verbose_name="Pays/Région",
                    ),
                ),
                (
                    "shipping_adress",
                    models.CharField(
                        max_length=50, verbose_name="situation géographique"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Monsieur", "Monsieur"),
                            ("Madame", "Madame"),
                            ("Mademoiselle", "Mademoiselle"),
                        ],
                        default="Monsieur",
                        max_length=12,
                        verbose_name="Civilité",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Célibataire", "Célibataire"),
                            ("Marié(e)", "Marié(e)"),
                            ("Veuf/ve", "Veuf/ve"),
                            ("Divorcé(e)", "Divorcé(e)"),
                            ("Fiancé(e)", "Fiancé(e)"),
                        ],
                        default="Célibataire",
                        max_length=100,
                        verbose_name="Situation matrimoniale",
                    ),
                ),
                (
                    "nationnality",
                    models.CharField(max_length=80, verbose_name="Nationalité"),
                ),
                (
                    "level_of_education",
                    models.CharField(
                        choices=[
                            (
                                "BEPEC - Certificat d'Etude Primaire et Elémentaire",
                                "BEPEC - Certificat d'Etude Primaire et Elémentaire",
                            ),
                            ("BAC - Baccalauréat", "BAC - Baccalauréat"),
                            (
                                "BTS - Brevet de Technicien Supérieur",
                                "BTS - Brevet de Technicien Supérieur",
                            ),
                            (
                                "DEUG - Diplôme d'Etudes Universitaires Générales",
                                "DEUG - Diplôme d'Etudes Universitaires Générales",
                            ),
                            ("Licence (1,2,3)", "Licence (1,2,3)"),
                            ("Master (1,2)", "Master (1,2)"),
                            (
                                "Autres- Spécifier dans la note ci-dessous",
                                "Autres- Spécifier dans la note ci-dessous",
                            ),
                        ],
                        default="BEPEC - Certificat d'Etude Primaire et Elémentaire",
                        max_length=100,
                        verbose_name="Niveau d'étude",
                    ),
                ),
                (
                    "local_market",
                    models.CharField(
                        max_length=100, verbose_name="Marché à proximité de vous"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, verbose_name="Activer le compte"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "distributeurs",
                "ordering": ["-created_at", "-active"],
            },
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="id_index",
        ),
        migrations.AlterField(
            model_name="user",
            name="civility",
            field=models.CharField(
                choices=[
                    ("Monsieur", "Monsieur"),
                    ("Madame", "Madame"),
                    ("Mademoiselle", "Mademoiselle"),
                ],
                default="Monsieur",
                max_length=12,
                verbose_name="civilité",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["id"], name="accounts_db_id_73b1c9_idx"),
        ),
        migrations.AddIndex(
            model_name="distributorcustomer",
            index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
