# Generated by Django 3.2.12 on 2022-11-29 02:40
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20221129_0211"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributorcustomer",
            name="shipping_adress",
        ),
        migrations.RemoveField(
            model_name="distributorcustomer",
            name="shipping_country",
        ),
        migrations.AddField(
            model_name="distributorcustomer",
            name="commune",
            field=models.CharField(max_length=180, null=True, verbose_name="Commune"),
        ),
        migrations.AddField(
            model_name="distributorcustomer",
            name="district",
            field=models.CharField(max_length=180, null=True, verbose_name="Quartier"),
        ),
        migrations.AddField(
            model_name="distributorcustomer",
            name="id_card_number",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="Numéro de votre pièce d'identité (CNI, PASSEPORT, PERMIS)",
            ),
        ),
        migrations.AddField(
            model_name="distributorcustomer",
            name="profession",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="distributorcustomer",
            name="year_old",
            field=models.PositiveIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(40),
                ],
                verbose_name="Votre âge",
            ),
        ),
    ]
