# Generated by Django 3.1.6 on 2021-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210208_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID STORE'),
        ),
    ]
