# Generated by Django 3.1.5 on 2021-01-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210109_2112'),
        ('accounts', '0002_auto_20210109_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='interested_customers', to='category.Category'),
        ),
    ]
