# Generated by Django 3.1.5 on 2021-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210109_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='civility',
            field=models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='Mr', max_length=4, verbose_name='civilité'),
        ),
    ]
