# Generated by Django 3.2.12 on 2022-11-29 03:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auto_20221129_0240"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributorcustomer",
            name="year_old",
        ),
        migrations.AddField(
            model_name="distributorcustomer",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Votre date de naisssance"),
        ),
    ]
