# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210208_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='civility',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='M.', max_length=4, verbose_name='civilité'),
        ),
    ]
