# Generated by Django 3.2.12 on 2022-11-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20221129_0314"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distributorcustomer",
            old_name="shipping_first_name",
            new_name="fullname",
        ),
        migrations.RemoveField(
            model_name="distributorcustomer",
            name="shipping_last_name",
        ),
        migrations.AlterField(
            model_name="distributorcustomer",
            name="level_of_education",
            field=models.CharField(
                choices=[
                    (
                        "CEPE - Certificat d'Etude Primaire et Elémentaire",
                        "CEPEC - Certificat d'Etude Primaire et Elémentaire",
                    ),
                    (
                        "BEPC - Brevet d’Étude du Premier Cycle",
                        "BEPC - Brevet d’Étude du Premier Cycle",
                    ),
                    ("BAC - Baccalauréat", "BAC - Baccalauréat"),
                    (
                        "BTS - Brevet de Technicien Supérieur",
                        "BTS - Brevet de Technicien Supérieur",
                    ),
                    (
                        "DEUG - Diplôme d'Etudes Universitaires Générales",
                        "DEUG - Diplôme d'Etudes Universitaires Générales",
                    ),
                    ("Licence (1,2,3)", "Licence (1,2,3)"),
                    ("Master (1,2)", "Master (1,2)"),
                    (
                        "Autres- Spécifier dans la note ci-dessous",
                        "Autres- Spécifier dans la note ci-dessous",
                    ),
                ],
                default="CEPE - Certificat d'Etude Primaire et Elémentaire",
                max_length=100,
                verbose_name="Niveau d'étude",
            ),
        ),
    ]
