# Generated by Django 3.2.12 on 2022-11-29 04:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_auto_20221129_0445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributorcustomer",
            name="delivery_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=6,
                null=True,
                unique=True,
                verbose_name="ID Distributeur",
            ),
        ),
        migrations.AlterField(
            model_name="distributorcustomer",
            name="ip_address",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                null=True,
                verbose_name="Adresse IP",
            ),
        ),
    ]
