# Generated by Django 3.2.12 on 2022-11-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20221129_0446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributorcustomer",
            name="ip_address",
        ),
    ]
