# Generated by Django 3.2.12 on 2022-12-01 13:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_distributorcustomer_delivery_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributorcustomer",
            name="delivery_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID Distributeur",
            ),
        ),
        migrations.AlterField(
            model_name="distributorcustomer",
            name="fullname",
            field=models.CharField(max_length=50, verbose_name="Nom & Prénoms"),
        ),
    ]
