# Generated by Django 3.1.6 on 2021-02-08 19:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='sous-catégorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category', verbose_name='catégorie principale'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together={('parent', 'name')},
        ),
    ]
