# Generated by Django 3.1.6 on 2021-02-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210208_1906'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category_db',
        ),
    ]
