# Generated by Django 3.1.7 on 2021-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Commande reçue - en cours de traitement', 'Commande reçue - en cours de traitement'), ('Commande en cours de livraison', 'Commande en cours de livraison'), ('Commande reçue', 'Commande reçue'), ('Commande annulée', 'Commande annulée')], default='Commande reçue - en cours de traitement', max_length=120, verbose_name='status'),
        ),
    ]
