# Generated by Django 3.1.6 on 2021-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Soumis', 'Soumis'), ('En cours de livraison', 'Commande en cours de livraison'), ('Commande reçue', 'Commande reçue'), ('Commande annulée', 'Commande annulée')], default='Soumis', max_length=26, verbose_name='status'),
        ),
    ]
