# Generated by Django 3.2.12 on 2022-10-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(choices=[(None, 'Veuillez sélectionner un pays'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Sénégal', 'Sénégal'), ('Togo', 'Togo'), ('Burkina Faso', 'Burkina Faso'), ('Cameroun', 'Cameroun'), ('Congo RDC CDF', 'Congo RDC CDF'), ('Guinée', 'Guinée'), ('Congo RDC USD', 'Congo RDC USD'), ('Niger', 'Niger'), ('Benin', 'Benin'), ('Mali', 'Mali'), ('Comores', 'Comores')], max_length=25, verbose_name='Pays/Région'),
        ),
    ]
