# Generated by Django 3.2.12 on 2022-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collecte_data",
            field=models.BooleanField(
                default=False, verbose_name="Message de satisfaction"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("commande livrée", "commande livrée"),
                    ("commande annulée", "commande annulée"),
                    ("traitement en cours", "traitement en cours"),
                    ("livraison en cours", "livraison en cours"),
                ],
                default="traitement en cours",
                max_length=120,
                verbose_name="status",
            ),
        ),
    ]
