# Generated by Django 3.1.6 on 2021-02-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emailing',
            field=models.BooleanField(default=False, verbose_name='abonnement aux offres et promotions'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='date ajout'),
        ),
    ]
