# Generated by Django 3.1.6 on 2021-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210215_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Soumis', 'Soumis'), ('Traitée', 'Traitée'), ('Expédié', 'Expédié'), ('Annulé', 'Annulé')], default='Soumis', max_length=7, verbose_name='status de le commande'),
        ),
    ]
