# Generated by Django 3.1.7 on 2021-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210227_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Commande en cours de traitement', 'Commande en cours de traitement'), ('Commande en cours de livraison', 'Commande en cours de livraison'), ('Commande livrée', 'Commande livrée'), ('Commande annulée', 'Commande annulée')], default='Commande en cours de traitement', max_length=120, verbose_name='status'),
        ),
    ]
