# Generated by Django 3.2.12 on 2022-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_shipping_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(choices=[(None, 'Veuillez sélectionner un pays'), ("Côte d'Ivoire", "Côte d'Ivoire")], default="Côte d'Ivoire", max_length=25, verbose_name='Pays/Région'),
        ),
    ]
