# Generated by Django 3.2.12 on 2022-12-01 13:32
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_auto_20221201_1332"),
        ("checkout", "0002_auto_20221129_0728"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir un livreur",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distibutors",
                to="accounts.distributorcustomer",
                verbose_name="livreur",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="collecte_data",
            field=models.BooleanField(
                default=False, verbose_name="Message de satisfaction envoyé"
            ),
        ),
    ]
