# Generated by Django 3.1.5 on 2021-01-13 22:11

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, help_text='Selectionner la/les catégorie(s) du produit.', on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='catégorie'),
            preserve_default=False,
        ),
    ]
