# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-updated', '-timestamp'], 'verbose_name_plural': 'images du produit'},
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image_db',
        ),
    ]
