# Generated by Django 3.1.5 on 2021-01-12 04:01

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='ancien tarif'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Comma-delimited set of SEO keywords for keywords meta tag', to='catalogue.Tagulous_Product_keywords', verbose_name='mots clés'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique value for product page URL, created automatically from name.', verbose_name='URL du produit'),
        ),
    ]
