# Generated by Django 3.2.12 on 2023-06-16 09:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                help_text="Selectionner la catégorie du produit.",
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
                verbose_name="catégorie",
            ),
        ),
    ]
