# Generated by Django 3.1.5 on 2021-01-10 00:57

import core.utils
from django.db import migrations, models
import mptt.fields
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210109_2205'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(help_text='Selectionner la/les catégorie(s) du produit.', to='category.Category', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Définir votre produit.', verbose_name='description du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_image_path, verbose_name='image descriptif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='mettre le produit en promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(default=True, help_text='produit en stock', verbose_name='en stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Définir quelques mots clés.', to='catalogue.Tagulous_Product_keywords', verbose_name='mots clés'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='prix de vente du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='lien du prouit. Il est auto-générer, mais vous pouvez le modifier.', verbose_name='URL du produit'),
        ),
    ]
