# Generated by Django 3.1.7 on 2021-04-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210307_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Le nom du produit', max_length=255, verbose_name='nom du produit'),
        ),
    ]
