# Generated by Django 3.1.5 on 2021-01-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210112_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="date d'ajout automatique du produit.", verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date de mise à jour automatique du produit.', verbose_name='date de mise à jour'),
        ),
    ]
