# Generated by Django 3.1.7 on 2021-02-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210221_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
