# Generated by Django 3.1.6 on 2021-02-15 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0003_auto_20210211_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(help_text='Le magasin en charge de la vente.', limit_choices_to={'is_seller': True, 'is_staff': True, 'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='vendeur'),
        ),
    ]
