# Generated by Django 3.1.6 on 2021-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20210215_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=50, null=True, verbose_name='prix normal'),
        ),
    ]
