# Generated by Django 3.1.5 on 2021-01-21 10:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_auto_20210121_1050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, verbose_name='note')),
                ('content', models.TextField(verbose_name='avis client')),
                ('created_time_at', models.DateField(auto_now_add=True)),
                ('created_hour_at', models.TimeField(auto_now_add=datetime.datetime(2021, 1, 21, 10, 50, 30, 766625, tzinfo=utc))),
                ('is_approved', models.BooleanField(default=False, verbose_name='approuvé ?')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product', verbose_name='produit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Avis des clients',
                'db_table': 'reviews_db',
                'ordering': ['-rating', '-created_time_at', '-created_time_at'],
                'get_latest_by': ['-created_time_at', '-created_time_at', '-rating'],
            },
        ),
    ]
