# Generated by Django 3.1.5 on 2021-01-26 01:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0010_auto_20210126_0104'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productreview',
            managers=[
                ('approved', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_hour_at',
            field=models.TimeField(auto_now_add=datetime.datetime(2021, 1, 26, 1, 39, 51, 488645, tzinfo=utc)),
        ),
    ]
