# Generated by Django 3.1.5 on 2021-01-28 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20210128_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_hour_at',
            field=models.TimeField(auto_now_add=datetime.datetime(2021, 1, 28, 18, 2, 7, 627463, tzinfo=utc)),
        ),
    ]
