# Generated by Django 3.1.6 on 2021-02-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=50, verbose_name='mot recherché')),
                ('ip_address', models.CharField(max_length=225, verbose_name='adresse IP')),
                ('date_search_at', models.DateField(auto_now_add=True, verbose_name='date de recherche')),
                ('time_search_at', models.TimeField(auto_now=True, verbose_name='heure de la recherche')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'recherche',
                'db_table': 'search_db',
                'ordering': ['-date_search_at', '-time_search_at'],
                'get_latest_by': ['-date_search_at', '-time_search_at'],
            },
        ),
    ]
