# Generated by Django 3.1.5 on 2021-01-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchterm',
            options={'ordering': ['-date_search_at', '-time_search_at'], 'verbose_name_plural': 'recherche'},
        ),
    ]
