# Generated by Django 3.1.5 on 2021-01-12 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='pays')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='région')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='ville')),
                ('street', models.CharField(max_length=200, verbose_name='quartier/rue')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('phone_1', models.CharField(max_length=20, verbose_name='téléphone')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone 2')),
            ],
            options={
                'verbose_name_plural': 'adresse de livraison',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_order', models.CharField(blank=True, max_length=10, verbose_name='ID de la commande')),
                ('payed', models.FloatField(blank=True, default=0.0, verbose_name='montant')),
                ('payed_date', models.DateTimeField(blank=True, null=True, verbose_name='date de paiement')),
                ('is_payed', models.BooleanField(default=False, verbose_name='paiement effectué')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name="date d'expédition")),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='date de la livraison')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('is_direct_pay', models.BooleanField(default=False, verbose_name='paiement direct')),
                ('cancelReason', models.TextField(blank=True, null=True, verbose_name="motifs d'annulation")),
                ('is_canceled', models.BooleanField(default=False, verbose_name='annulé')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ManyToManyField(to='cart.CartItem', verbose_name='panier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'commandes',
                'ordering': ['-timestamp', '-modify_date'],
                'index_together': {('track_order',)},
            },
        ),
    ]
