# Generated by Django 3.1.5 on 2021-01-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20210128_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='adresse ip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='adresse postal (optionnel)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='id de la commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='coût total'),
        ),
    ]
